version: '3.8'

services:
  todo-db:
    image: postgres:15-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  todo-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: todo_django
    command: sh -c "python manage.py migrate --fake-initial && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=todo-db
      - DB_NAME=todo_db
      - DB_USER=todo_user
      - DB_PASSWORD=todo_password
      - DB_PORT=5432
    depends_on:
      todo-db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: